trigger:
  batch: true
  branches:
    include:
    - develop
    - master
  paths:
    include:
    - 'services/techhubkeda/'

pool:
  vmImage: 'ubuntu-latest'

variables:
- name: 'projectlocation'
  value: '$(Agent.BuildDirectory)/s'

stages:
  - stage: Keda
    jobs:
      - job: CopyFilesIaCAndPublish
        steps:
        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(System.DefaultWorkingDirectory)/services/techhubkeda/'
            Contents: '**'
            TargetFolder: '$(Build.ArtifactStagingDirectory)/keda'
            CleanTargetFolder: true
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)/keda'
            ArtifactName: 'Keda'
            publishLocation: 'Container'