apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: #{KEDA_AUTH_NAME}#
  namespace: #{NAMESPACE}#
spec:
  secretTargetRef:
    - key: #{KEDA_KEY}#
      name: #{KEDA_CREDS_NAME}#
      parameter: #{KEDA_AZURE_PARAM}#