apiVersion: v2
name: langfuse
version: 0.12.1
description: Open source LLM engineering platform - LLM observability, metrics, evaluations, prompt management.
type: application
keywords:
  - langfuse
  - llm
  - observability
  - prompt management
  - metrics
home: https://langfuse.com/
sources:
  - https://github.com/langfuse/langfuse
  - https://github.com/langfuse/langfuse-k8s
dependencies:
  - name: postgresql
    version: 16.4.9
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.deploy
  - name: clickhouse
    version: 8.0.5
    repository: https://charts.bitnami.com/bitnami
    condition: clickhouse.deploy
  - name: valkey
    version: 2.2.4
    repository: https://charts.bitnami.com/bitnami
    condition: valkey.deploy
  - name: minio
    version: 14.10.5
    repository: https://charts.bitnami.com/bitnami
    condition: minio.deploy
maintainers:
  - name: langfuse
    email: contact@langfuse.com
    url: https://langfuse.com/
icon: https://langfuse.com/langfuse_logo.png
appVersion: "3.54.0"
