trigger:
  batch: true
  branches:
    include:
    - develop
    - release/v*
    - master
  paths:
    include:
    - 'helm/langfuse/*'
    - 'services/techhublangfuse/*'

variables:
- group: Variables para CI

pool:
  vmImage: '$(vmImageName)'

stages:
  - stage: LangfuseArtifact
    jobs:
      - job: CopyFilesHelmAndPublish
        steps:
          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(System.DefaultWorkingDirectory)/helm/langfuse'
              Contents: '**'
              TargetFolder: '$(Build.ArtifactStagingDirectory)/helm/langfuse'
              CleanTargetFolder: true
            displayName: 'Copy Files helm Langfuse'
          - task: PublishPipelineArtifact@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)/helm/langfuse'
              ArtifactName: 'Helm-Langfuse'
              publishLocation: 'Container'
            displayName: 'Publish artifacts Langfuse'