trigger:
  batch: true
  branches:
    include:
    - develop
    - release/v*
    - master
  paths:
    include:
    - 'helm/langfuse/*'
    - 'services/techhublangfuse/*'

variables:
- group: Variables para CI

pool:
  vmImage: '$(vmImageName)'

stages:
  - stage: LangfuseArtifact
    jobs:
      # - job: CopyFilesHelmAndPublish
      #   steps:
      #     - task: CopyFiles@2
      #       inputs:
      #         SourceFolder: '$(System.DefaultWorkingDirectory)/helm/langfuse'
      #         Contents: '**'
      #         TargetFolder: '$(System.DefaultWorkingDirectory)/helm/langfuse'
      #         CleanTargetFolder: true
      #       displayName: 'Copy Files helm Langfuse'
      #     - task: PublishPipelineArtifact@1
      #       inputs:
      #         PathtoPublish: '$(Build.ArtifactStagingDirectory)/helm/langfuse'
      #         ArtifactName: 'Helm-Langfuse'
      #         publishLocation: 'Container'
      #       displayName: 'Publish artifacts Langfuse'
      - job: CopyFilesHelmAndPublish
        steps:
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(Pipeline.Workspace)/s/helm/langfuse'
              artifact: 'Helm-Langfuse'
            displayName: 'Publish artifacts Langfuse'