// This code is property of the GGAO // 


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Text.Json.Serialization;
using System.Linq;
using System.Threading.Tasks;
using techhubapigw.Database.DTOs;

namespace techhubapigw.Models
{
    public class ApiKey
    {
        // Used as Primary key
        public string Key { get; set; }
        public DateTime Created { get; set; }

        // Used as index to report ussage (optional: autogenerated if null)
        public string ReportId { get; set; }
        public string Department { get; set; }
        public string TenantId { get; set; }

        //public IReadOnlyCollection<string> Roles { get; set; }
        public List<string> Roles { get; set; }

        // Limits and metrics to query
        public ICollection<UsageLimit> Limits { get; set; } = new Collection<UsageLimit>();

        [JsonIgnore]
        public ICollection<Metric> Metrics { get; set; } = new Collection<Metric>();
    }
}
