trigger:
  batch: true
  branches:
    include:
    - develop
    - release/v*
    - master
  paths:
    include:
    - 'services/techhubelasticsearch/'

pool:
  vmImage: 'ubuntu-latest'

variables:
- name: 'projectlocation'
  value: '$(Agent.BuildDirectory)/s'
- name: 'folderName'
  value: techhubelasticsearch
- name: 'targetFolderName'
  value: 'elasticsearch'

stages:
  - stage: Elasticsearch
    jobs:
      - job: CopyFilesIaCAndPublish
        steps:
        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(System.DefaultWorkingDirectory)/services/$(folderName)/'
            Contents: '**'
            TargetFolder: '$(Build.ArtifactStagingDirectory)/$(targetFolderName)'
            CleanTargetFolder: true
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(targetFolderName)'
            ArtifactName: 'ElasticSearch'
            publishLocation: 'Container'       