{{- if .Values.keda.enabled_object }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Release.Name }}--keda
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    name: {{ .Release.Name }}
  minReplicaCount: {{ .Values.keda.min_replicas }}
  maxReplicaCount: {{ .Values.keda.max_replicas }}
  pollingInterval: 10
  cooldownPeriod: 30
  triggers:
    - type: {{ .Values.keda.keda_type }}
      metadata:
        queueName: {{ .Values.keda.queue_name }}
        messageCount: {{ .Values.keda.msg_count }}
      authenticationRef:
        name: {{ .Values.keda.keda_auth_name }}
{{- end }}