### This code is property of the GGAO ###


trigger:
  batch: true
  branches:
    include:
    - develop
    - release/v*
    - master
  paths:
    include:
    - 'services/techhubgenaillmapi/*'
    - 'helm/'

variables:
- group: Variables para CI
- group: Params Python
- group: RegistryVariables

- name: serviceName
  value: 'techhubgenaillmapi'
- name:  projectName
  value: 'TechHubGlobalToolkit'
- name:  vmImageName
  value: 'ubuntu-20.04'
- name:  pythonVersion
  value: '$(python_version)'
- name:  baseImage
  value: '$(default_base)'
- name:  registryServerName
  value: '$(registryName).azurecr.io'
- name: acrRegistryLogin
  value: '$(registryLogin)'
- name: acrRegistryPassword
  value: '$(registryPassword)'
- name: templateType
  value: 'microservicesgenai'
- name: helmRepoLocation
  value: '$(Agent.BuildDirectory)/s/helm'
- name: helmVersion
  value: '$(helmVer)'
- name: projectLocation
  value: '$(Agent.BuildDirectory)/s/services'
- name: description
  value: 'Microservice to genai. API based in languages models'
- name: feedGenai
  value: '$(feed_genai)'

stages:
- stage: SonarAnalysis
  jobs:
    - job: test
      continueOnError: false
      steps:      
      - script: |
          python -m venv .venv
          source .venv/bin/activate
          pip install pytest pytest-cov
          pytest services/techhubgenaillmapi/test --cov=services/techhubgenaillmapi --cov-report=xml:services/techhubgenaillmapi/test/coverage.xml
        displayName: 'Run Tests and Generate Coverage' 
      - task: SonarQubePrepare@7
        inputs:
          SonarQube: 'sonarqube_service_connection_techhub_dev_japaneast'
          scannerMode: 'cli'
          configMode: 'manual'
          cliProjectKey: $(System.DefinitionName)
          cliSources: |
                $(System.DefaultWorkingDirectory)/services/techhubgenaillmapi/,
                $(System.DefaultWorkingDirectory)/helm/
          extraProperties: |
              sonar.projectVersion=1.0
              sonar.sources=$(System.DefaultWorkingDirectory)/services/techhubgenaillmapi/
              sonar.python.coverage.reportPaths=coverage.xml

          # removes sonar.branch.name variable as this is not supported by community edition
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            $params = "$env:SONARQUBE_SCANNER_PARAMS" -replace '"sonar.branch.name":"[\w,/,-]*"\,?'
                Write-Host "##vso[task.setvariable variable=SONARQUBE_SCANNER_PARAMS]$params"      
      - task: SonarQubeAnalyze@7
        inputs:
          jdkversion: 'JAVA_HOME_17_X64'

      - task: SonarQubePublish@7
        inputs:
          pollingTimeoutSec: '300'

- stage: Building
  displayName: Build image
  jobs:
  - job:
    pool:
      vmImage: $(vmImageName)
    steps:
    - template: ../ap-template.yml
      parameters:
        serviceName: '$(serviceName)'
        registryServerName: '$(registryServerName)'
        acrRegistryLogin:  '$(acrRegistryLogin)'
        acrRegistryPassword:  '$(acrRegistryPassword)'
        defaultWorkingDirectory: '$(system.defaultWorkingDirectory)'
        sourcesDirectory: '$(projectLocation)/$(serviceName)'
        tag: '$(Build.BuildNumber)'
        pythonVersion: '$(pythonVersion)'
        baseImage: '$(baseImage)'
        projectLocation: '$(projectLocation)'
        helmRepoLocation: '$(helmRepoLocation)'
        helmVersion: '$(helmVersion)'
        templateType: '$(templateType)'
        description: '$(description)'
        libraryFeed: '$(feedGenai)'