### This code is property of the GGAO ###


trigger:
  batch: true
  branches:
    include:
    - develop
    - release/v*
    - master
  paths:
    include:
    - 'services/techhubflowmgmtchecktimeout/*'
    - 'helm/'

variables:
- group: Variables para CI
- group: Params Python
- group: RegistryVariables
- group: Sonarqube Params

- name: serviceName
  value: 'techhubflowmgmtchecktimeout'
- name:  projectName
  value: 'TechHubGlobalToolkit'
- name:  pythonVersion
  value: '$(python_version)'
- name:  baseImage
  value: '$(default_base)'
- name:  registryServerName
  value: '$(registryName).azurecr.io'
- name: acrRegistryLogin
  value: '$(registryLogin)'
- name: acrRegistryPassword
  value: '$(registryPassword)'
- name: templateType
  value: 'microservicesgenai'
- name: helmRepoLocation
  value: '$(Agent.BuildDirectory)/s/helm'
- name: helmVersion
  value: '$(helmVer)'
- name: projectLocation
  value: '$(Agent.BuildDirectory)/s/services'
- name: description
  value: 'Microservice to flow management. Check timeout in Redis and reports it'
- name: feedGenai
  value: '$(feed_genai)'

stages:
- stage: SonarAnalysis
  displayName: Sonar analysis and test coverage
  jobs:
  - job:
    continueOnError: true
    pool:
      vmImage: '$(vmImageName)'
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(pythonVersion)'
          addToPath: true
          architecture: 'x64'
        displayName: Set Python version

      - script: |
            echo "---Install magic---"
            sudo apt-get install libmagic1

            python -m venv .venv
            source .venv/bin/activate

            cd $(System.DefaultWorkingDirectory)/imagesbase/$(baseImage)
            echo "---Installing requirements from $(pwd)---"
            pip install -r requirements.txt

            echo "---Installing requirements from $(pwd)---"
            cd $(System.DefaultWorkingDirectory)/libraries/genai_sdk_services

            pip install --upgrade pip
            python -m pip install -U setuptools wheel twine
            python setup.py install

            echo "---Build Library---" 
            python setup.py build_ext --inplace
            python setup.py bdist_wheel --python-tag=cp$(python_version)

            echo "---$(serviceName)---"
            cd $(System.DefaultWorkingDirectory)/services/$(serviceName)/

            echo "---Installing requirements from $(pwd)---"
            pip install -r requirements.txt
            pip install pytest pytest-cov 

            export PYTHONPATH=$(System.DefaultWorkingDirectory)/services/
            echo "---Running coverage---"
            coverage run --source=$(System.DefaultWorkingDirectory)/services/$(serviceName)/ -m pytest -s
            coverage report
            coverage xml
        displayName: Coverage report

      - task: SonarQubePrepare@7
        inputs:
          SonarQube: $(sonarqube_service_connection)
          scannerMode: 'cli'
          configMode: 'manual'
          cliProjectKey: $(System.DefinitionName)
          cliSources: '$(System.DefaultWorkingDirectory)/services/$(serviceName)/'
          extraProperties: |
              sonar.projectVersion=1.0
              sonar.sources=$(System.DefaultWorkingDirectory)/services/$(serviceName)/
              sonar.python.coverage.reportPaths=$(System.DefaultWorkingDirectory)/services/$(serviceName)/coverage.xml
              sonar.exclusions=**/test/**
        displayName: Sonar Preprare

      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            $params = "$env:SONARQUBE_SCANNER_PARAMS" -replace '"sonar.branch.name":"[\w\.,/,-]*"\,?'
                Write-Host "##vso[task.setvariable variable=SONARQUBE_SCANNER_PARAMS]$params"   
        displayName: Remove parameter

      - task: SonarQubeAnalyze@7
        inputs:
          jdkversion: 'JAVA_HOME_17_X64'
        displayName: Sonar Analyze

      - task: SonarQubePublish@7
        inputs:
          pollingTimeoutSec: '300'
        displayName: Sonar Publish

- stage: Building
  displayName: Build image Docker and Trivy scan
  jobs:
  - job:
    pool:
      vmImage: '$(vmImageName)'
    steps:
    - template: ../ap-template.yml
      parameters:
        serviceName: '$(serviceName)'
        registryServerName: '$(registryServerName)'
        acrRegistryLogin:  '$(acrRegistryLogin)'
        acrRegistryPassword:  '$(acrRegistryPassword)'
        defaultWorkingDirectory: '$(system.defaultWorkingDirectory)'
        sourcesDirectory: '$(projectLocation)/$(serviceName)'
        tag: '$(Build.BuildNumber)'
        pythonVersion: '$(pythonVersion)'
        baseImage: '$(baseImage)'
        projectLocation: '$(projectLocation)'
        helmRepoLocation: '$(helmRepoLocation)'
        helmVersion: '$(helmVersion)'
        templateType: '$(templateType)'
        description: '$(description)'
        libraryFeed: '$(feedGenai)'