### This code is property of the GGAO ###


trigger:
  batch: true
  branches:
    include: 
    - develop
    - release/v*
    - master
  paths:
    include:
    - default-base

variables:
- group: Params Python
- group: Variables para CI
- group: RegistryVariables

- name: imageName
  value: '$(default_base)'
- name: vmImageName
  value: 'ubuntu-latest'
- name: pythonVersion
  value: '$(python_version)'
- name: feedGenai
  value: '$(feed_genai)'
- name: libraryVersion
  value: '$(library)'
- name:  registryServerName
  value: '$(registryName).azurecr.io'
- name: acrRegistryLogin
  value: '$(registryLogin)'
- name: acrRegistryPassword
  value: '$(registryPassword)'

stages:
- stage: Building
  displayName: Build image
  jobs:
  - job:
    pool:
      vmImage: $(vmImageName)
    steps:
    - template: ../ap-template.yml
      parameters:
        imageName: '$(imageName)'
        defaultWorkingDirectory: '$(system.defaultWorkingDirectory)/$(imageName)'
        sourcesDirectory: '$(Build.SourcesDirectory)/$(imageName)'
        tag: '$(Build.BuildNumber)'
        pythonVersion: '$(pythonVersion)'
        libraryFeed: '$(feedGenai)'
        registryServerName: '$(registryServerName)'
        acrRegistryLogin: '$(acrRegistryLogin)'
        acrRegistryPassword: '$(acrRegistryPassword)'
        libraryVersion: '$(libraryVersion)'